AIM:Program to implement Naive Bayes algorithm using any standard dataset available in public domain and find the accuracy of the algorithm

In [192]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [193]:
dataset=pd.read_csv('/content/Iris.csv')

In [194]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [195]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [196]:
from sklearn.preprocessing import StandardScaler

In [197]:
scalar=StandardScaler()

In [198]:
scalar.fit(dataset.drop('Species',axis=1))

StandardScaler()

In [199]:
y=scalar.transform(dataset.drop('Species',axis=1))

In [200]:
from sklearn.model_selection import train_test_split

In [201]:
x=dataset.drop('Species',axis=1)
x

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [202]:
import pandas as pd
x=pd.DataFrame(dataset.drop('Species',axis=1))

In [203]:
x

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [204]:
y=pd.DataFrame(dataset['Species'])
y

Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [205]:
x_train,x_test,y_train,y_test=train_test_split(x,y,stratify=y,random_state=120,test_size=0.2)

In [206]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB

In [207]:
classifier=GaussianNB()

In [208]:
classifier.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [209]:
y_pred=classifier.predict(x_test)

In [210]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [211]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00        10
 Iris-virginica       1.00      1.00      1.00        10

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [212]:
print(confusion_matrix(y_test,y_pred))

[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [213]:
print(accuracy_score(y_test,y_pred))

1.0


Result:Program executed successfully and output obtained
